/**
 * AUTO-GENERATED by dyapi-cli. DO NOT EDIT BY HAND.
 *
 * Regenerate with:  dyapi gen <backend-dir> --out <this-file>
 *
 * Models: 11 · Controller routes: 28
 */
/* eslint-disable */
import axios, { type AxiosInstance, type AxiosRequestConfig } from "axios";


export interface DyapiClientOptions {
  /** Base URL of the dyapi server, e.g. "https://api.example.com". */
  baseURL?: string;
  /** JWT token; sent as the `X-DYAPI-Token` header when set. */
  token?: string;
  /** Send cookies with requests (dyapi cookieLogin mode). Defaults to true. */
  withCredentials?: boolean;
  /** Provide a preconfigured axios instance to fully override the default. */
  instance?: AxiosInstance;
  /**
   * Whether this client should unwrap the axios response to its body (`response.data`).
   * Defaults to true. Set to FALSE only when the injected `instance` already unwraps
   * in its own response interceptor (e.g. `interceptors.response.use(r => r.data)`),
   * otherwise the body would be unwrapped twice and total/pages silently disappear.
   */
  unwrap?: boolean;
}

let _token: string | undefined;
let _unwrap = true;

let _client: AxiosInstance = axios.create({
  baseURL: "",
  withCredentials: true,
});

/** Configure the shared axios client used by all generated functions. */
export function configureApi(options: DyapiClientOptions = {}): void {
  if (options.instance) {
    _client = options.instance;
  } else {
    _client = axios.create({
      baseURL: options.baseURL ?? "",
      withCredentials: options.withCredentials ?? true,
    });
  }
  if (options.token !== undefined) setToken(options.token);
  if (options.unwrap !== undefined) _unwrap = options.unwrap;
}

/** Set (or clear) the JWT token attached as the `X-DYAPI-Token` header. */
export function setToken(token: string | undefined): void {
  _token = token;
}

/** Access the underlying axios instance (for interceptors, etc.). */
export function getClient(): AxiosInstance {
  return _client;
}

async function request<T>(config: AxiosRequestConfig): Promise<T> {
  const headers = { ...(config.headers ?? {}) };
  if (_token) (headers as Record<string, string>)["X-DYAPI-Token"] = _token;
  const res = await _client.request({ ...config, headers });
  // Default: unwrap axios response to its body. If an injected instance already
  // unwrapped (configureApi with unwrap:false), res IS the body — return as-is.
  return (_unwrap ? (res as any).data : res) as T;
}


/* ---------------- Common response envelopes ---------------- */

export interface ListResponse<T> {
  code: number;
  data: T[];
  total: number;
  pages: number;
}

export interface OneResponse<T> {
  code: number;
  data: T;
}

export interface CreateResponse {
  code: number;
  /** Newly created record id (or the raw container result for bulk inserts). */
  id: any;
}

export interface UpdateResponse {
  code: number;
  /** Number of affected rows. */
  length: number;
}

export interface DeleteResponse {
  code: number;
}

/** MongoDB-style filter passed to dyapi read/update/delete queries. */
export type DyapiFilter = Record<string, any>;

/** Query parameters accepted by dyapi CRUD read endpoints. */
export interface ReadQuery {
  id?: string | number;
  filter?: DyapiFilter;
  orderBy?: string;
  orderDesc?: boolean;
  limit?: number;
  page?: number;
  offset?: number;
  fields?: string[];
  hideFields?: string[];
  pops?: string[];
}

const READQUERY_KEYS = new Set([
  "id", "filter", "orderBy", "orderDesc", "limit", "page", "offset", "fields", "hideFields", "pops",
]);

/** Serialize a ReadQuery into dyapi's expected query-string shape; pass custom keys through verbatim. */
function toReadParams(q: ReadQuery & Record<string, any> = {}): Record<string, any> {
  const p: Record<string, any> = {};
  if (q.id !== undefined) p.id = q.id;
  if (q.filter !== undefined) p.filter = JSON.stringify(q.filter);
  if (q.orderBy !== undefined) p.orderBy = q.orderBy;
  if (q.orderDesc !== undefined) p.orderDesc = q.orderDesc;
  if (q.limit !== undefined) p.limit = q.limit;
  if (q.page !== undefined) p.page = q.page;
  if (q.offset !== undefined) p.offset = q.offset;
  if (q.fields !== undefined) p.fields = q.fields.join(",");
  if (q.hideFields !== undefined) p.hideFields = q.hideFields.join(",");
  if (q.pops !== undefined) p.pops = q.pops.join(",");
  // Custom query keys (from HTTP* overrides) pass through unchanged.
  for (const k in q) if (!READQUERY_KEYS.has(k) && q[k] !== undefined) p[k] = q[k];
  return p;
}


/* ---------------- Generic CRUD (for runtime/dynamic models) ---------------- */

export interface CrudApi<T = any> {
  list(query?: ReadQuery): Promise<ListResponse<T>>;
  get(id: string | number, query?: ReadQuery): Promise<OneResponse<T>>;
  create(body: Partial<T> | Partial<T>[]): Promise<CreateResponse>;
  update(id: string | number, body: Partial<T>): Promise<UpdateResponse>;
  remove(id: string | number): Promise<DeleteResponse>;
}

/**
 * Generic CRUD client for models that static analysis cannot see — e.g. models
 * created at runtime via dyapi's dynamic modeling (ModelInjector / deriveClass).
 * `route` is the @CRUD route segment, e.g. crud("schemas") -> /api/schemas.
 */
export function crud<T = any>(route: string): CrudApi<T> {
  const base = "/api" + "/" + String(route).replace(/^\/+|\/+$/g, "");
  return {
    list: (query) => request({ method: "get", url: base, params: toReadParams(query) }),
    get: (id, query) => request({ method: "get", url: base + "/" + id, params: toReadParams(query) }),
    create: (body) => request({ method: "post", url: base, data: body }),
    update: (id, body) => request({ method: "put", url: base + "/" + id, data: body }),
    remove: (id) => request({ method: "delete", url: base + "/" + id }),
  };
}


/* ============================================================
 * Model: ArticleModel  ->  /api/articles
 * ============================================================ */
export interface Article {
  id: number;
  title: string;
  slug: string;
  author_id: string;
  description: string;
  thumbnail: string;
  content: string;
  content_template: string;
  status: string;
  publish_at: string;
  rev_version: number;
  is_top: number;
  audience: string;
  teaser: number;
  access_eff: string;
  category_id: number;
  published_at: string;
  created_at: string;
  updated_at: string;
  data: any;
}

export interface ArticleCreateInput {
  title: string;
  slug: string;
  author_id?: string;
  description?: string;
  thumbnail?: string;
  content?: string;
  content_template?: string;
  status?: string;
  publish_at?: string;
  rev_version?: number;
  is_top?: number;
  audience?: string;
  teaser?: number;
  access_eff?: string;
  category_id: number;
  published_at?: string;
  created_at?: string;
  updated_at?: string;
  data?: any;
}

export interface ArticleUpdateInput {
  title?: string;
  slug?: string;
  author_id?: string;
  description?: string;
  thumbnail?: string;
  content?: string;
  content_template?: string;
  status?: string;
  publish_at?: string;
  rev_version?: number;
  is_top?: number;
  audience?: string;
  teaser?: number;
  access_eff?: string;
  category_id?: number;
  published_at?: string;
  created_at?: string;
  updated_at?: string;
  data?: any;
}

/** GET /api/articles — list Article records (paginated). */
export function listArticle(query?: ReadQuery): Promise<ListResponse<Article>> {
  return request({ method: "get", url: "/api/articles", params: toReadParams(query) });
}

/** GET /api/articles/:id — fetch a single Article. */
export function getArticle(id: string | number, query?: ReadQuery): Promise<OneResponse<Article>> {
  return request({ method: "get", url: "/api/articles" + "/" + id, params: toReadParams(query) });
}

/** POST /api/articles — create one (or many) Article. */
export function createArticle(body: ArticleCreateInput | ArticleCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/articles", data: body });
}

/** PUT /api/articles/:id — update a Article by id. */
export function updateArticle(id: string | number, body: ArticleUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/articles" + "/" + id, data: body });
}

/** DELETE /api/articles/:id — remove a Article by id. */
export function removeArticle(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/articles" + "/" + id });
}


/* ============================================================
 * Model: AttachmentModel  ->  /api/attachments
 * ============================================================ */
export interface Attachment {
  id: number;
  filename: string;
  url: string;
  mime_type: string;
  size: number;
  storage_provider: string;
  uploader_id: number;
}

export interface AttachmentCreateInput {
  filename: string;
  url: string;
  mime_type?: string;
  size?: number;
  storage_provider?: string;
  uploader_id?: number;
}

export interface AttachmentUpdateInput {
  filename?: string;
  url?: string;
  mime_type?: string;
  size?: number;
  storage_provider?: string;
  uploader_id?: number;
}

/** GET /api/attachments — list Attachment records (paginated). */
export function listAttachment(query?: ReadQuery): Promise<ListResponse<Attachment>> {
  return request({ method: "get", url: "/api/attachments", params: toReadParams(query) });
}

/** GET /api/attachments/:id — fetch a single Attachment. */
export function getAttachment(id: string | number, query?: ReadQuery): Promise<OneResponse<Attachment>> {
  return request({ method: "get", url: "/api/attachments" + "/" + id, params: toReadParams(query) });
}

/** POST /api/attachments — create one (or many) Attachment. */
export function createAttachment(body: AttachmentCreateInput | AttachmentCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/attachments", data: body });
}

/** PUT /api/attachments/:id — update a Attachment by id. */
export function updateAttachment(id: string | number, body: AttachmentUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/attachments" + "/" + id, data: body });
}

/** DELETE /api/attachments/:id — remove a Attachment by id. */
export function removeAttachment(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/attachments" + "/" + id });
}


/* ============================================================
 * Model: CategoryModel  ->  /api/categories
 * ============================================================ */
export interface Category {
  id: number;
  name: string;
  slug: string;
  parent_id: number;
  list_template: string;
  content_template: string;
  weight: number;
  audience: string;
  teaser: number;
  article_data_fields: any;
  data: any;
}

export interface CategoryCreateInput {
  name: string;
  slug: string;
  parent_id?: number;
  list_template?: string;
  content_template?: string;
  weight?: number;
  audience?: string;
  teaser?: number;
  article_data_fields?: any;
  data?: any;
}

export interface CategoryUpdateInput {
  name?: string;
  slug?: string;
  parent_id?: number;
  list_template?: string;
  content_template?: string;
  weight?: number;
  audience?: string;
  teaser?: number;
  article_data_fields?: any;
  data?: any;
}

/** GET /api/categories — list Category records (paginated). */
export function listCategory(query?: ReadQuery): Promise<ListResponse<Category>> {
  return request({ method: "get", url: "/api/categories", params: toReadParams(query) });
}

/** GET /api/categories/:id — fetch a single Category. */
export function getCategory(id: string | number, query?: ReadQuery): Promise<OneResponse<Category>> {
  return request({ method: "get", url: "/api/categories" + "/" + id, params: toReadParams(query) });
}

/** POST /api/categories — create one (or many) Category. */
export function createCategory(body: CategoryCreateInput | CategoryCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/categories", data: body });
}

/** PUT /api/categories/:id — update a Category by id. */
export function updateCategory(id: string | number, body: CategoryUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/categories" + "/" + id, data: body });
}

/** DELETE /api/categories/:id — remove a Category by id. */
export function removeCategory(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/categories" + "/" + id });
}


/* ============================================================
 * Model: MenuModel  ->  /api/menus
 * ============================================================ */
export interface Menu {
  id: number;
  name: string;
  location: string;
  items: any;
}

export interface MenuCreateInput {
  name: string;
  location?: string;
  items?: any;
}

export interface MenuUpdateInput {
  name?: string;
  location?: string;
  items?: any;
}

/** GET /api/menus — list Menu records (paginated). */
export function listMenu(query?: ReadQuery): Promise<ListResponse<Menu>> {
  return request({ method: "get", url: "/api/menus", params: toReadParams(query) });
}

/** GET /api/menus/:id — fetch a single Menu. */
export function getMenu(id: string | number, query?: ReadQuery): Promise<OneResponse<Menu>> {
  return request({ method: "get", url: "/api/menus" + "/" + id, params: toReadParams(query) });
}

/** POST /api/menus — create one (or many) Menu. */
export function createMenu(body: MenuCreateInput | MenuCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/menus", data: body });
}

/** PUT /api/menus/:id — update a Menu by id. */
export function updateMenu(id: string | number, body: MenuUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/menus" + "/" + id, data: body });
}

/** DELETE /api/menus/:id — remove a Menu by id. */
export function removeMenu(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/menus" + "/" + id });
}


/* ============================================================
 * Model: ResourceGrantModel  ->  /api/resource_grants
 * ============================================================ */
export interface ResourceGrant {
  id: number;
  model: string;
  resource_id: number;
  grantee_type: string;
  grantee_id: number;
  access: string;
  granted_by: number;
  created_at: string;
}

export interface ResourceGrantCreateInput {
  model: string;
  resource_id: number;
  grantee_type: string;
  grantee_id: number;
  access: string;
  granted_by?: number;
  created_at?: string;
}

export interface ResourceGrantUpdateInput {
  model?: string;
  resource_id?: number;
  grantee_type?: string;
  grantee_id?: number;
  access?: string;
  granted_by?: number;
  created_at?: string;
}

/** GET /api/resource_grants — list ResourceGrant records (paginated). */
export function listResourceGrant(query?: ReadQuery): Promise<ListResponse<ResourceGrant>> {
  return request({ method: "get", url: "/api/resource_grants", params: toReadParams(query) });
}

/** GET /api/resource_grants/:id — fetch a single ResourceGrant. */
export function getResourceGrant(id: string | number, query?: ReadQuery): Promise<OneResponse<ResourceGrant>> {
  return request({ method: "get", url: "/api/resource_grants" + "/" + id, params: toReadParams(query) });
}

/** POST /api/resource_grants — create one (or many) ResourceGrant. */
export function createResourceGrant(body: ResourceGrantCreateInput | ResourceGrantCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/resource_grants", data: body });
}

/** PUT /api/resource_grants/:id — update a ResourceGrant by id. */
export function updateResourceGrant(id: string | number, body: ResourceGrantUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/resource_grants" + "/" + id, data: body });
}

/** DELETE /api/resource_grants/:id — remove a ResourceGrant by id. */
export function removeResourceGrant(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/resource_grants" + "/" + id });
}


/* ============================================================
 * Model: RevisionModel  ->  /api/revisions
 * ============================================================ */
export interface Revision {
  id: number;
  content_type: string;
  content_id: string;
  version_no: number;
  data: any;
  author_id: string;
  note: string;
  status_at_snapshot: string;
  created_at: string;
}

export interface RevisionCreateInput {
  content_type: string;
  content_id: string;
  version_no: number;
  data?: any;
  author_id?: string;
  note?: string;
  status_at_snapshot?: string;
  created_at?: string;
}

export interface RevisionUpdateInput {
  content_type?: string;
  content_id?: string;
  version_no?: number;
  data?: any;
  author_id?: string;
  note?: string;
  status_at_snapshot?: string;
  created_at?: string;
}

/** GET /api/revisions — list Revision records (paginated). */
export function listRevision(query?: ReadQuery): Promise<ListResponse<Revision>> {
  return request({ method: "get", url: "/api/revisions", params: toReadParams(query) });
}

/** GET /api/revisions/:id — fetch a single Revision. */
export function getRevision(id: string | number, query?: ReadQuery): Promise<OneResponse<Revision>> {
  return request({ method: "get", url: "/api/revisions" + "/" + id, params: toReadParams(query) });
}

/** POST /api/revisions — create one (or many) Revision. */
export function createRevision(body: RevisionCreateInput | RevisionCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/revisions", data: body });
}

/** PUT /api/revisions/:id — update a Revision by id. */
export function updateRevision(id: string | number, body: RevisionUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/revisions" + "/" + id, data: body });
}

/** DELETE /api/revisions/:id — remove a Revision by id. */
export function removeRevision(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/revisions" + "/" + id });
}


/* ============================================================
 * Model: RoleModel  ->  /api/roles
 * ============================================================ */
export interface Role {
  id: number;
  name: string;
  label: string;
  description: string;
  is_system: number;
}

export interface RoleCreateInput {
  name: string;
  label?: string;
  description?: string;
  is_system?: number;
}

export interface RoleUpdateInput {
  name?: string;
  label?: string;
  description?: string;
  is_system?: number;
}

/** GET /api/roles — list Role records (paginated). */
export function listRole(query?: ReadQuery): Promise<ListResponse<Role>> {
  return request({ method: "get", url: "/api/roles", params: toReadParams(query) });
}

/** GET /api/roles/:id — fetch a single Role. */
export function getRole(id: string | number, query?: ReadQuery): Promise<OneResponse<Role>> {
  return request({ method: "get", url: "/api/roles" + "/" + id, params: toReadParams(query) });
}

/** POST /api/roles — create one (or many) Role. */
export function createRole(body: RoleCreateInput | RoleCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/roles", data: body });
}

/** PUT /api/roles/:id — update a Role by id. */
export function updateRole(id: string | number, body: RoleUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/roles" + "/" + id, data: body });
}

/** DELETE /api/roles/:id — remove a Role by id. */
export function removeRole(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/roles" + "/" + id });
}


/* ============================================================
 * Model: RolePermissionModel  ->  /api/role_permissions
 * ============================================================ */
export interface RolePermission {
  id: number;
  role_id: number;
  model: string;
  action: string;
  scope: string;
}

export interface RolePermissionCreateInput {
  role_id: number;
  model: string;
  action: string;
  scope?: string;
}

export interface RolePermissionUpdateInput {
  role_id?: number;
  model?: string;
  action?: string;
  scope?: string;
}

/** GET /api/role_permissions — list RolePermission records (paginated). */
export function listRolePermission(query?: ReadQuery): Promise<ListResponse<RolePermission>> {
  return request({ method: "get", url: "/api/role_permissions", params: toReadParams(query) });
}

/** GET /api/role_permissions/:id — fetch a single RolePermission. */
export function getRolePermission(id: string | number, query?: ReadQuery): Promise<OneResponse<RolePermission>> {
  return request({ method: "get", url: "/api/role_permissions" + "/" + id, params: toReadParams(query) });
}

/** POST /api/role_permissions — create one (or many) RolePermission. */
export function createRolePermission(body: RolePermissionCreateInput | RolePermissionCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/role_permissions", data: body });
}

/** PUT /api/role_permissions/:id — update a RolePermission by id. */
export function updateRolePermission(id: string | number, body: RolePermissionUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/role_permissions" + "/" + id, data: body });
}

/** DELETE /api/role_permissions/:id — remove a RolePermission by id. */
export function removeRolePermission(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/role_permissions" + "/" + id });
}


/* ============================================================
 * Model: UserModel  ->  /api/users
 * ============================================================ */
export interface User {
  id: number;
  username: string;
  password: string;
  nickname: string;
  role: string;
  lastontime: string;
}

export interface UserCreateInput {
  username?: string;
  password?: string;
  nickname?: string;
  role?: string;
  lastontime?: string;
}

export interface UserUpdateInput {
  username?: string;
  password?: string;
  nickname?: string;
  role?: string;
  lastontime?: string;
}

/** GET /api/users — list User records (paginated). */
export function listUser(query?: ReadQuery): Promise<ListResponse<User>> {
  return request({ method: "get", url: "/api/users", params: toReadParams(query) });
}

/** GET /api/users/:id — fetch a single User. */
export function getUser(id: string | number, query?: ReadQuery): Promise<OneResponse<User>> {
  return request({ method: "get", url: "/api/users" + "/" + id, params: toReadParams(query) });
}

/** POST /api/users — create one (or many) User. */
export function createUser(body: UserCreateInput | UserCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/users", data: body });
}

/** PUT /api/users/:id — update a User by id. */
export function updateUser(id: string | number, body: UserUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/users" + "/" + id, data: body });
}

/** DELETE /api/users/:id — remove a User by id. */
export function removeUser(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/users" + "/" + id });
}


/* ============================================================
 * Model: UserRoleModel  ->  /api/user_roles
 * ============================================================ */
export interface UserRole {
  id: number;
  user_id: number;
  role_id: number;
}

export interface UserRoleCreateInput {
  user_id: number;
  role_id: number;
}

export interface UserRoleUpdateInput {
  user_id?: number;
  role_id?: number;
}

/** GET /api/user_roles — list UserRole records (paginated). */
export function listUserRole(query?: ReadQuery): Promise<ListResponse<UserRole>> {
  return request({ method: "get", url: "/api/user_roles", params: toReadParams(query) });
}

/** GET /api/user_roles/:id — fetch a single UserRole. */
export function getUserRole(id: string | number, query?: ReadQuery): Promise<OneResponse<UserRole>> {
  return request({ method: "get", url: "/api/user_roles" + "/" + id, params: toReadParams(query) });
}

/** POST /api/user_roles — create one (or many) UserRole. */
export function createUserRole(body: UserRoleCreateInput | UserRoleCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/user_roles", data: body });
}

/** PUT /api/user_roles/:id — update a UserRole by id. */
export function updateUserRole(id: string | number, body: UserRoleUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/user_roles" + "/" + id, data: body });
}

/** DELETE /api/user_roles/:id — remove a UserRole by id. */
export function removeUserRole(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/user_roles" + "/" + id });
}


/* ============================================================
 * Model: ContentSchemaModel  ->  /api/schemas
 * ============================================================ */
export interface ContentSchema {
  id: number;
  modelName: string;
  tableName: string;
  routePath: string;
  schemaDefinition: any;
  createdAt: string;
}

export interface ContentSchemaCreateInput {
  modelName: string;
  tableName: string;
  routePath: string;
  schemaDefinition: any;
  createdAt?: string;
}

export interface ContentSchemaUpdateInput {
  modelName?: string;
  tableName?: string;
  routePath?: string;
  schemaDefinition?: any;
  createdAt?: string;
}

/** GET /api/schemas — list ContentSchema records (paginated). */
export function listContentSchema(query?: ReadQuery): Promise<ListResponse<ContentSchema>> {
  return request({ method: "get", url: "/api/schemas", params: toReadParams(query) });
}

/** GET /api/schemas/:id — fetch a single ContentSchema. */
export function getContentSchema(id: string | number, query?: ReadQuery): Promise<OneResponse<ContentSchema>> {
  return request({ method: "get", url: "/api/schemas" + "/" + id, params: toReadParams(query) });
}

/** POST /api/schemas — create one (or many) ContentSchema. */
export function createContentSchema(body: ContentSchemaCreateInput | ContentSchemaCreateInput[]): Promise<CreateResponse> {
  return request({ method: "post", url: "/api/schemas", data: body });
}

/** PUT /api/schemas/:id — update a ContentSchema by id. */
export function updateContentSchema(id: string | number, body: ContentSchemaUpdateInput): Promise<UpdateResponse> {
  return request({ method: "put", url: "/api/schemas" + "/" + id, data: body });
}

/** DELETE /api/schemas/:id — remove a ContentSchema by id. */
export function removeContentSchema(id: string | number): Promise<DeleteResponse> {
  return request({ method: "delete", url: "/api/schemas" + "/" + id });
}

/* ============================================================
 * Controllers
 * ============================================================ */

/** GET /api/acl/:model/:resourceId — AclController.list */
export function aclList(model: string | number, resourceId: string | number): Promise<{ code: number; data: any; }> {
  return request({ method: "get", url: `/api/acl/${model}/${resourceId}` });
}


export interface AclCreateBody {
  grantee_type?: any;
  grantee_id?: any;
  access?: any;
}

/** POST /api/acl/:model/:resourceId — AclController.create */
export function aclCreate(model: string | number, resourceId: string | number, body?: AclCreateBody): Promise<{ code: number; data: { id: any; updated: boolean; }; } | { code: number; data: { id: any; }; }> {
  return request({ method: "post", url: `/api/acl/${model}/${resourceId}`, data: body });
}


/** DELETE /api/acl/:model/:resourceId/:grantId — AclController.remove */
export function aclRemove(model: string | number, resourceId: string | number, grantId: string | number): Promise<{ code: number; }> {
  return request({ method: "delete", url: `/api/acl/${model}/${resourceId}/${grantId}` });
}


/** GET /api/content/home — ContentController.getHome */
export function contentGetHome(): Promise<{ code: number; data: { articles: any[]; categories: any[]; }; }> {
  return request({ method: "get", url: "/api/content/home" });
}


/** GET /api/content/article — ContentController.getArticle */
export function contentGetArticle(query?: { slug?: string }): Promise<{ code: number; data: any; }> {
  return request({ method: "get", url: "/api/content/article", params: query });
}


/** GET /api/content/articles — ContentController.listArticles */
export function contentListArticles(query?: { fields?: string; filter?: string; limit?: string; orderBy?: string; orderDesc?: string; page?: string }): Promise<{ code: number; data: any[]; total: any; pages: any; }> {
  return request({ method: "get", url: "/api/content/articles", params: query });
}


export interface ContentPreviewTokenBody {
  id?: any;
}

/** POST /api/content/preview-token — ContentController.previewToken */
export function contentPreviewToken(body?: ContentPreviewTokenBody): Promise<{ code: number; data: { token: string; }; }> {
  return request({ method: "post", url: "/api/content/preview-token", data: body });
}


/** GET /api/content/preview — ContentController.preview */
export function contentPreview(query?: { id?: string; pt?: string }): Promise<{ code: number; data: { preview: boolean; article: any; category: any; breadcrumbs: any[]; template: any; }; }> {
  return request({ method: "get", url: "/api/content/preview", params: query });
}


/** GET /api/content/category — ContentController.getCategory */
export function contentGetCategory(query?: { slug?: string }): Promise<{ code: number; data: any; }> {
  return request({ method: "get", url: "/api/content/category", params: query });
}


/** GET /api/content/categories — ContentController.listCategories */
export function contentListCategories(): Promise<{ code: number; data: any[]; }> {
  return request({ method: "get", url: "/api/content/categories" });
}


export interface LifecycleTransitionBody {
  to?: any;
  publish_at?: any;
  note?: any;
}

/** POST /api/lifecycle/:type/:id/transition — ContentLifecycleController.transition */
export function lifecycleTransition(type: string | number, id: string | number, body?: LifecycleTransitionBody): Promise<{ code: number; message: string; }> {
  return request({ method: "post", url: `/api/lifecycle/${type}/${id}/transition`, data: body });
}


/** GET /api/lifecycle/:type/:id/revisions — ContentLifecycleController.listRevisions */
export function lifecycleListRevisions(type: string | number, id: string | number): Promise<{ code: number; data: any[]; }> {
  return request({ method: "get", url: `/api/lifecycle/${type}/${id}/revisions` });
}


export interface LifecycleRollbackBody {
  version_no?: any;
}

/** POST /api/lifecycle/:type/:id/rollback — ContentLifecycleController.rollback */
export function lifecycleRollback(type: string | number, id: string | number, body?: LifecycleRollbackBody): Promise<{ code: number; message: string; }> {
  return request({ method: "post", url: `/api/lifecycle/${type}/${id}/rollback`, data: body });
}


/** GET /api/lifecycle/manageable-categories — ContentLifecycleController.manageableCategories */
export function lifecycleManageableCategories(query?: { action?: string }): Promise<{ code: number; data: { scope: string; categories: any; }; }> {
  return request({ method: "get", url: "/api/lifecycle/manageable-categories", params: query });
}


/** GET /api/schematools/all — SchemaDevController.getAllSchemas */
export function schematoolsGetAllSchemas(): Promise<{ code: number; data: { modelName: any; tableName: any; routePath: any; rbacActions: any; ownerField: any; fields: any; }[]; }> {
  return request({ method: "get", url: "/api/schematools/all" });
}


/** GET /api/system/config — SystemController.getConfig */
export function systemGetConfig(): Promise<{ code: number; data: any; }> {
  return request({ method: "get", url: "/api/system/config" });
}


/** POST /api/system/config — SystemController.updateConfig */
export function systemUpdateConfig(body?: any): Promise<{ code: number; message: string; }> {
  return request({ method: "post", url: "/api/system/config", data: body });
}


/** GET /api/system/status — SystemController.status */
export function systemStatus(): Promise<{ code: number; data: { is_initialized: boolean; }; }> {
  return request({ method: "get", url: "/api/system/status" });
}


/** POST /api/system/restart — SystemController.restart */
export function systemRestart(body?: any): Promise<{ code: number; message: string; }> {
  return request({ method: "post", url: "/api/system/restart", data: body });
}


export interface SystemSetupBody {
  siteName?: any;
  adminUsername?: any;
  adminPassword?: any;
  importData?: any;
}

/** POST /api/system/setup — SystemController.setup */
export function systemSetup(body?: SystemSetupBody): Promise<{ code: number; data: Record<string, { imported: number; failed: number; }>; saltState: "match" | "mismatch" | "unknown"; resetCredentials: { username: string; password: string; }[]; message: string; } | { code: number; message: string; }> {
  return request({ method: "post", url: "/api/system/setup", data: body });
}


/** GET /api/system/export — SystemController.exportData */
export function systemExportData(): Promise<{ code: number; data: { _meta: { version: string; exportedAt: string; generator: string; saltFingerprint: string; }; }; }> {
  return request({ method: "get", url: "/api/system/export" });
}


/** POST /api/upload — UploadController.uploadFile */
export function uploadUploadFile(body?: any): Promise<{ code: number; data: any[]; }> {
  return request({ method: "post", url: "/api/upload", data: body });
}


/** DELETE /api/upload/:id — UploadController.deleteFile */
export function uploadDeleteFile(id: string | number): Promise<{ code: number; message: string; }> {
  return request({ method: "delete", url: `/api/upload/${id}` });
}


/** GET /api/upload/providers — UploadController.getProviders */
export function uploadGetProviders(): Promise<{ code: number; data: { activeProvider: string; storageConfig: { [key: string]: any; provider: string; }; providers: any[]; }; }> {
  return request({ method: "get", url: "/api/upload/providers" });
}


export interface UploadTestStorageBody {
  provider?: any;
}

/** POST /api/upload/test — UploadController.testStorage */
export function uploadTestStorage(body?: UploadTestStorageBody): Promise<{ code: number; data: { provider: any; success: boolean; }; } | { code: number; data: { provider: any; success: boolean; note: string; }; }> {
  return request({ method: "post", url: "/api/upload/test", data: body });
}


export interface UserLoginBody {
  username: string;
  password: string;
}

/** POST /api/user/login — UserController.login */
export function userLogin(body: UserLoginBody): Promise<{ code: number; message: string; data: { id: any; username: any; role: any; }; }> {
  return request({ method: "post", url: "/api/user/login", data: body });
}


/** POST /api/user/logout — UserController.logout */
export function userLogout(body?: any): Promise<{ code: number; message: string; }> {
  return request({ method: "post", url: "/api/user/logout", data: body });
}


/** GET /api/user/loginInfo — UserController.loginInfo */
export function userLoginInfo(): Promise<{ code: number; message: string; data: any; exp: any; auth: { roles: any; isSuperAdmin: boolean; permissions: { model: string; action: string; scope: string; }[]; }; }> {
  return request({ method: "get", url: "/api/user/loginInfo" });
}

