import { createI18n } from 'vue-i18n';

const messages = {
  en: {
    toast: { categoryUpdated: "Category updated", categoryCreated: "Category created", categoryDeleted: "Category deleted", menuUpdated: "Menu updated", menuCreated: "Menu created", menuDeleted: "Menu deleted", userUpdated: "User updated", userCreated: "User created", userDeleted: "User deleted", saved: "Saved", savedSettings: "Settings saved", saveFailed: "Save failed", deleted: "Deleted", deleteFailed: "Delete failed", articleDeleted: "Article deleted", fileDeleted: "File deleted", fileDeleteFailed: "Could not delete the file", published: "Published", hidden: "Hidden", scheduled: "Scheduled", scheduleCancelled: "Schedule cancelled", rolledBack: "Rolled back to v{v}", granted: "Access granted", roleCreated: "Role created", roleDeleted: "Role deleted", permissionAdded: "Permission added", exported: "Data exported", exportFailed: "Export failed", restarting: "Backend is restarting — refresh in a moment", restartFailed: "Restart failed", connectionOk: "Connection successful", connectionFailed: "Connection test failed", connectionNotPassed: "Connection test did not pass", loggedOut: "Signed out" },
    validate: { selectCategory: "Pick a category", selectPublishTime: "Pick a publish time", selectGrantee: "Pick who to grant access to", selectPermission: "Pick at least one permission", roleNameRequired: "Role key is required", systemRoleUndeletable: "Built-in roles cannot be deleted", modelRequired: "Model (table name) is required, e.g. articles" },
    setup: { saltMismatch: "The PASSWORD_SALT on this server differs from the one the export was made with, so none of the imported password hashes work. Every account password has been reset to the random value below.", saltMismatchHint: "This list is shown once and is not stored anywhere. Save it now, then ask everyone to change their password after signing in.", saltUnknown: "This export predates salt fingerprinting, so password hashes were kept as-is. If nobody can sign in, this server's PASSWORD_SALT differs from the source site's.", copyAll: "Copy all", copied: "Copied", savedThemGoOn: "I saved them — continue", importHint: "Choose an NFCMS export file; everything will be restored from it.", pickExportFile: "Choose an export file (.json)", importAndInit: "Import and initialise", completeSetup: "Complete setup", invalidFile: "Not an NFCMS export file.", parseFailed: "Could not read the file: {err}", unknownError: "Unknown error", pickFile: "Choose a data file to import.", importFailed: "Import failed", tabNew: "New site", tabImport: "Import data", importReportTitle: "Import finished with problems", importReportHint: "Rows that failed were NOT imported. Anything referencing them may be wrong. Reset the database and retry rather than continuing on a partial import.", importRowsFailed: "{n} row(s) failed", importColsDropped: "dropped column(s): {cols}", importGoOn: "Continue anyway" },
    system: { noAdminAccess: "No admin access", noAdminAccessHint: "Your account has no management permissions. Ask an administrator if you need access.", requestFailed: "Request failed", title: "NFCMS", visitSite: "Visit Site", dashboard: "Overview", content: "Content", systemProps: "System", menus: "Menus", categories: "Categories", articles: "Articles", schemas: "Schemas", settings: "Settings", users: "Users", roles: "Roles & Permissions", files: "Files Library", loading: "Loading...", noEntries: "No entries found." },
    action: { openInNewWindow: "Open in new window", cancel: "Cancel", remove: "Remove", new: "New", edit: "Edit", delete: "Delete", save: "Save", saveDraft: "Save Draft", publish: "Publish", publishNow: "Publish now", unpublish: "Hide", schedule: "Schedule…", updateSchedule: "Update time", cancelSchedule: "Cancel schedule", close: "Close", rollback: "Rollback", revoke: "Revoke", share: "Share", confirmDelete: "Are you sure you want to delete this?", search: "Search...", generate: "Generate", addRootItem: "Add Root Item", addSub: "Sub", restart: "Restart Backend", upload: "Upload", export: "Export", import: "Import" },
    contentStatus: { hidden: "Hidden", scheduled: "Scheduled", visible: "Visible" },
    confirm: { restartBackend: "Restart the backend?", deleteRole: "Delete role \"{name}\"?", deleteRecord: "Delete this record permanently?", title: "Please confirm", accept: "Confirm", reject: "Cancel", rollbackMsg: "Roll back to version v{v}? The current content will first be saved as a new version." },
    common: { prev: "Prev", next: "Next" },
    userPicker: { title: "Select a user", search: "Search username…", empty: "No users found" },
    fileUploader: { chooseFromLibrary: "Choose from library", pickTitle: "Select a file", search: "Search filename...", empty: "No files yet", uploading: "Uploading...", uploadFailed: "Upload failed", dropHint: "Click to upload", replace: "Replace", removeConfirm: "Remove this file from the field? (The file itself stays in the library.)", copyLink: "Copy link", copied: "Link copied", copyFailed: "Copy failed — select the URL manually", selectedN: "{n} selected" },
    access: { title: "Access", audience: "Audience", audienceHint: "Who may view this on the public site. Inherited from the parent category; the strictest level in the chain wins.", teaser: "Show in article lists", teaserHint: "When restricted: keep the card in public lists (title/summary only) and show a sign-in prompt instead of a 404.", teaserOn: "Summary shown", teaserOff: "Fully hidden", effective: "In effect", fromAudience: "audience inherited from 「{name}」", fromTeaser: "summary setting from 「{name}」", inheritedGrants: "Inherited from parent categories", noticeDraft: "This is still a draft, so the settings below don't apply yet. They take effect once published.", noticeScheduled: "Publishing automatically at {time}; the settings below take effect then.", who: "Who can see this", tierInherit: "Follow the category's setting", tierInheritOf: "Follow 「{name}」's setting", tierPublic: "Anyone", tierAuthenticated: "Signed-in users", tierRestricted: "Only chosen people or roles", categoryNow: "Category is currently: {level}", inheritedSuffix: " (inherited from 「{name}」)", teaserLocked: "「{name}」 is set to fully hidden, so the summary can't be shown here.", teaserTightenHint: "The category shows summaries; unchecking hides this one completely — an article can only be stricter than its category, never looser.", tooLooseHint: "「{name}」 is limited to 「{level}」, so this can't be loosened here.", thisCategory: "the category", emptyListWarn: "No one is on the list yet, so nobody can open this (apart from administrators).", people: "Access & collaboration", authorRow: "Author · always able to edit", inheritedFrom: "from category 「{name}」", readOnly: "read-only", redundantView: "Currently visible to anyone, so this has no effect right now.", immediate: "Changes here take effect immediately — no need to save.", newArticleHint: "Save the article first, then you can set permissions.", addPerson: "Add person", perm_view: "Can view", perm_edit: "Can edit", perm_manage: "Can manage", perm_custom: "Custom", customIs: "Currently: {list}", act_view: "view on the public site", act_read: "read", act_update: "edit", act_delete: "delete", act_publish: "publish" },
    acl: { granteeUser: "User", granteeRole: "Role", none: "No grants yet", add: "Grant", pickUser: "Select user…", pickRole: "Select role…", categoryArticles: "Article access in this category", categoryArticlesHint: "Users/roles granted here can manage articles in this category and its subcategories (cascades).", categoryAudience: "Who may VIEW restricted articles here", categoryAudienceHint: "For categories set to \"Only chosen people or roles\". Cascades to subcategories. This is view-only access on the public site — it grants no editing rights.", shareView: "Allow public viewing (V)" },
    profile: { title: "My profile", roleReadonly: "changed by an administrator only" },
    roles: { desc: "super_admin has every permission automatically. Grant other roles by model + action + scope; 'own' means only content they created or were shared.", primaryRole: "Primary role", additionalRoles: "Additional roles", additionalHint: "Effective permissions = primary ∪ additional roles", noOtherRoles: "No other roles", model: "Model (table)", act: "Action", scope: "Scope", noPerms: "No permissions yet — this role can only read default public content.", superAll: "super_admin automatically has all permissions; nothing to configure here.", addPerm: "Add", newRole: "New role", roleKey: "key e.g. reviewer", roleLabel: "Display name (optional)", selectPane: "Select a role on the left to manage permissions.", builtin: "built-in", readOnly: "Read (R)", readWrite: "Read/Write (R,U)", readWriteDelete: "R,U,D", pickUser: "Select user…", pickRole: "Select role…", targetUser: "User", targetRole: "Role", categoryGrants: "Category-scoped article access", categoryGrantsHint: "Let this role create & manage articles within specific categories (cascades to subcategories) — without granting blanket article access.", noCategoryGrants: "No category grants yet.", pickCategory: "Select category…", audienceGrants: "Viewable restricted categories", audienceGrantsHint: "Let this role VIEW restricted content in specific categories on the public site (cascades to subcategories). View-only — no editing rights.", noAudienceGrants: "No audience grants yet." },
    form: { icpPlaceholder: "e.g. 京ICP备xxxxxxx号", mourningOff: "Off", mourningOn: "On (site-wide greyscale)", name: "Name", nickname: "Nickname", parent_id: "Parent Category", none: "None", thumbnail: "Thumbnail img", list_template: "List Template", extraData: "Metadata (JSON)", title: "Title", slug: "Slug", status: "Status", date: "Date", actions: "Actions", urlSlug: "URL Slug", excerpt: "Excerpt", description: "Description", category_id: "Category", content_template: "Template", visible: "Visible", is_top: "Top", published_at: "Publish date", weight: "Weight", published: "Published", draft: "Draft", selectCategory: "Select Category", locationKey: "Location Key", generateRecursively: "Generate from Category", generateDesc: "Builds a nested menu from a category's subcategories. Pick \"All root categories\" to get one top-level item per root category.", generateFromRoot: "All root categories", menuItems: "Menu Items (Tree)", customUrl: "Custom URL", category: "Category", article: "Article", selectArticle: "Select Article", label: "Label", url: "URL (e.g. /about)", username: "Username", password: "Password", role: "Role", leaveBlankToKeep: "Leave blank to keep unchanged", admin: "Admin", superadmin: "Super Admin", site_name: "Site Name", subtitle: "Subtitle", icp_record: "ICP Record", mourning_mode: "Mourning Mode", articleDataFields: "Article Data Fields", articleDataFieldsDesc: "Define custom fields for articles in this category.", editorHint: "Editor hint", editorHintDesc: "Markdown, shown above the body editor for articles in this category — document the body format authors must follow.", editorHintPlaceholder: "e.g. which blocks the body must contain, and their format", fieldTitle: "Title", fieldTypeText: "Text", fieldTypeTextarea: "Long Text", fieldTypeNumber: "Number", fieldTypeAttachment: "Attachment", extraFields: "Custom Fields", exportTitle: "Export Data", exportDesc: "Export all site data to a JSON file. Import is only available during system setup.", exportAll: "Export All Data", storageProvider: "Storage Provider", storageConfig: "Storage Configuration", storageConfigDesc: "Configure where uploaded files are stored. Changing provider does not migrate existing files.", testConnection: "Test Connection", testSuccess: "Connection successful", testFailed: "Connection failed", testing: "Testing...", themeSettings: "Theme Settings", themeSettingsDesc: "Settings declared by the active front-end theme." },
    dashboard: { welcome: "Welcome", overviewPrefix: "This is your system dashboard. Keep track of your site data at a glance.", totalArticles: "Total Articles", schemasActive: "Active Schemas", totalCategories: "Total Categories", totalFiles: "Media Files", totalUsers: "Admins", recentArticles: "Recent Content", quickActions: "Quick Actions", systemStatus: "System Status" },
    auth: { logout: "Logout", signIn: "Sign In", useId: "Use your NFCMS ID.", username: "Username", password: "Password", loginFailed: "Login failed", loginSuccess: "Login Successful", fieldsRequired: "All fields are required." },
    front: { home: "Home", readMore: "Read More", back: "Back to Home", publishedOn: "Published on", by: "By", locked: "Members only", lockedHint: "Sign in to read" },
    gate: { title: "Restricted content", message: "This content is not publicly available. Sign in with an authorized account to continue.", login: "Sign in", backHome: "← Back to home" },
    article: { properties: "Properties", history: "Version History", scheduledAt: "Publishing automatically at {time}.", publishedAtHint: "Left empty, it is filled in when the article is first published." },
    menu: {},
    user: { new: "New User" },
    role: { super_admin: "Super Admin", admin: "Admin", user: "User", editor: "Editor" }
  },
  zh: {
    toast: { categoryUpdated: "分类更新成功", categoryCreated: "分类创建成功", categoryDeleted: "分类删除成功", menuUpdated: "菜单更新成功", menuCreated: "菜单创建成功", menuDeleted: "菜单删除成功", userUpdated: "用户更新成功", userCreated: "用户创建成功", userDeleted: "用户删除成功", saved: "已保存", savedSettings: "站点配置已保存", saveFailed: "保存失败", deleted: "删除成功", deleteFailed: "删除失败", articleDeleted: "文章删除成功", fileDeleted: "文件删除成功", fileDeleteFailed: "文件删除失败", published: "已发布", hidden: "已隐藏", scheduled: "已设为定时发布", scheduleCancelled: "已取消定时发布", rolledBack: "已回滚到 v{v}", granted: "已授予", roleCreated: "角色已创建", roleDeleted: "角色已删除", permissionAdded: "权限已添加", exported: "数据已导出", exportFailed: "导出失败", restarting: "后端正在重启，请稍后刷新页面", restartFailed: "重启失败", connectionOk: "连接测试成功", connectionFailed: "连接测试失败", connectionNotPassed: "连接测试未通过", loggedOut: "退出登录成功" },
    validate: { selectCategory: "请选择一个分类", selectPublishTime: "请选择发布时间", selectGrantee: "请选择被授权对象", selectPermission: "请至少选择一项权限", roleNameRequired: "角色标识必填", systemRoleUndeletable: "内置角色不可删除", modelRequired: "模型(表名)必填，如 articles" },
    setup: { saltMismatch: "本服务器的 PASSWORD_SALT 与导出方不同,导入的密码哈希全部失效。所有账号的密码已重置为下面的随机值。", saltMismatchHint: "这份清单只显示这一次,不会存在任何地方。请现在保存,并要求所有人登录后立即修改密码。", saltUnknown: "这份导出文件早于 salt 指纹机制,密码哈希已原样保留。如果所有人都登录不上,说明本机的 PASSWORD_SALT 与来源站点不同。", copyAll: "复制全部", copied: "已复制", savedThemGoOn: "已保存,继续", importHint: "选择之前导出的 NFCMS 数据文件，系统将从中恢复所有数据。", pickExportFile: "选择导出文件 (.json)", importAndInit: "导入并初始化", completeSetup: "完成初始化", invalidFile: "无效的导入文件格式（非 NFCMS 导出文件）", parseFailed: "文件解析失败：{err}", unknownError: "未知错误", pickFile: "请选择要导入的数据文件。", importFailed: "导入失败", tabNew: "新建站点", tabImport: "导入数据", importReportTitle: "导入完成,但有问题", importReportHint: "失败的行**没有**导入。任何引用它们的数据都可能是错的。建议重置数据库重来,而不是在一次残缺的导入上继续。", importRowsFailed: "{n} 行失败", importColsDropped: "丢弃了列:{cols}", importGoOn: "仍然继续" },
    system: { noAdminAccess: "无后台权限", noAdminAccessHint: "当前账号没有任何管理权限。如需访问请联系管理员。", requestFailed: "请求失败", title: "NFCMS", visitSite: "访问站点", dashboard: "仪表盘", content: "内容管理", systemProps: "系统设置", menus: "菜单管理", categories: "分类管理", articles: "文章管理", schemas: "模型字典", settings: "站点配置", users: "用户管理", roles: "角色与权限", files: "文件库", loading: "加载中...", noEntries: "未找到任何条目。" },
    action: { openInNewWindow: "新窗口打开", cancel: "取消", remove: "移除", new: "新建", edit: "编辑", delete: "删除", save: "保存", saveDraft: "存为草稿", publish: "发布", publishNow: "立即发布", unpublish: "隐藏", schedule: "定时发布…", updateSchedule: "更新时间", cancelSchedule: "取消定时", close: "关闭", rollback: "回滚", revoke: "撤销", share: "共享", confirmDelete: "您确定要删除此项 吗？", search: "搜索...", generate: "生成", addRootItem: "添加根节点", addSub: "添加子项", restart: "重启后端", upload: "上传文件", export: "导出", import: "导入" },
    contentStatus: { hidden: "隐藏", scheduled: "定时中", visible: "可见" },
    confirm: { restartBackend: "确定要重启后端吗？", deleteRole: "删除角色「{name}」？", deleteRecord: "永久删除这条记录？", title: "请确认", accept: "确认", reject: "取消", rollbackMsg: "回滚到版本 v{v}？当前内容会先存为一个新版本。" },
    common: { prev: "上一页", next: "下一页" },
    userPicker: { title: "选择用户", search: "搜索用户名…", empty: "未找到用户" },
    fileUploader: { chooseFromLibrary: "从文件库选择", pickTitle: "选择文件", search: "搜索文件名...", empty: "文件库还没有文件", uploading: "上传中...", uploadFailed: "上传失败", dropHint: "点击上传", replace: "替换", removeConfirm: "从该字段移除此文件？(文件本身仍保留在文件库中。)", copyLink: "复制链接", copied: "链接已复制", copyFailed: "复制失败，请手动选择地址", selectedN: "已选 {n} 个" },
    access: { title: "权限", audience: "访问受众", audienceHint: "谁能在公开站看到它。默认继承上级分类;沿分类链取最严的一级。", teaser: "显示在文章列表中", teaserHint: "受限时:仍在公开列表中保留卡片(仅标题/摘要),点开显示登录引导而不是 404。", teaserOn: "显示摘要", teaserOff: "完全隐藏", effective: "实际生效", fromAudience: "受众继承自「{name}」", fromTeaser: "摘要设置来自「{name}」", inheritedGrants: "从上级分类继承", noticeDraft: "本文还是草稿,下面的设置暂不生效。发布后按此生效。", noticeScheduled: "将于 {time} 自动发布,届时按下面的设置生效。", who: "谁能看到这篇", tierInherit: "跟随分类的设置", tierInheritOf: "跟随分类「{name}」的设置", tierPublic: "所有人", tierAuthenticated: "登录后可见", tierRestricted: "仅指定的人或角色", categoryNow: "分类当前:{level}", inheritedSuffix: "(继承自「{name}」)", teaserLocked: "分类「{name}」设为完全隐藏,这里无法显示摘要。", teaserTightenHint: "分类会显示摘要;取消勾选会让本文完全隐藏 —— 文章只能比分类更严,不能更宽松。", tooLooseHint: "分类「{name}」限定为「{level}」,这里无法放宽。", thisCategory: "所在分类", emptyListWarn: "名单还是空的,除管理员外没有人能打开这篇。", people: "访问与协作", authorRow: "作者 · 始终可编辑", inheritedFrom: "来自分类「{name}」", readOnly: "只读", redundantView: "当前对所有人可见,此项暂无作用。", immediate: "此处改动立即生效,无需保存。", newArticleHint: "先保存文章,然后就能设置权限了。", addPerson: "添加人员", perm_view: "可查看", perm_edit: "可编辑", perm_manage: "可管理", perm_custom: "自定义", customIs: "当前:{list}", act_view: "在公开站查看", act_read: "可读取", act_update: "可修改", act_delete: "可删除", act_publish: "可发布" },
    acl: { granteeUser: "用户", granteeRole: "角色", none: "暂无授权", add: "授予", pickUser: "选择用户…", pickRole: "选择角色…", categoryArticles: "本分类的文章权限", categoryArticlesHint: "在此授权的用户/角色可管理本分类及其子分类下的文章(级联生效)。", categoryAudience: "可访问本分类受限文章的用户/角色", categoryAudienceHint: "用于受众设为「仅指定的人或角色」的分类,级联到子分类。这只是公开站的**查看**权,不含任何编辑权。", shareView: "允许公开查看 (V)" },
    profile: { title: "我的资料", roleReadonly: "仅管理员可更改" },
    roles: { desc: "super_admin 自动拥有全部权限。为其它角色按「模型 + 动作 + 范围」授权;own 表示仅限本人创建或被共享的内容。", primaryRole: "主角色", additionalRoles: "附加角色", additionalHint: "有效权限 = 主角色 ∪ 附加角色", noOtherRoles: "无其它角色", model: "模型 (表名)", act: "动作", scope: "范围", noPerms: "暂无权限,该角色目前只能读取默认公开内容。", superAll: "super_admin 自动拥有一切权限,无需在此配置。", addPerm: "添加", newRole: "新建角色", roleKey: "标识 e.g. reviewer", roleLabel: "显示名(可选)", selectPane: "选择左侧一个角色以管理权限。", builtin: "内置", readOnly: "只读 (R)", readWrite: "读写 (R,U)", readWriteDelete: "读写删 (R,U,D)", pickUser: "选择用户…", pickRole: "选择角色…", targetUser: "用户", targetRole: "角色", categoryGrants: "分类文章授权", categoryGrantsHint: "让该角色在指定分类下创建与管理文章(级联到子分类)——无需授予全站文章权限。", noCategoryGrants: "暂无分类授权。", pickCategory: "选择分类…", audienceGrants: "可访问的受限分类", audienceGrantsHint: "让该角色在公开站可查看指定分类下的受限内容(级联到子分类)。只读,不含编辑权。", noAudienceGrants: "暂无受众授权。" },
    form: { icpPlaceholder: "如 京ICP备xxxxxxx号", mourningOff: "关闭", mourningOn: "开启 (全站置灰)", name: "名称", nickname: "昵称", parent_id: "上级分类", none: "无 (根节点)", thumbnail: "缩略图", list_template: "列表模板", extraData: "元数据 (JSON)", title: "标题", slug: "固定链接", status: "状态", date: "日期", actions: "操作", urlSlug: "URL 固定链接", excerpt: "摘要", description: "概述/描述", category_id: "分类目录", content_template: "渲染模板", visible: "可见状态", is_top: "置顶", published_at: "发布日期", weight: "排序权重", published: "已发布", draft: "草稿", selectCategory: "请选择分类", locationKey: "挂载位置(如header)", generateRecursively: "从分类递归生成", generateDesc: "按所选分类的子分类构建嵌套菜单。选「全部根分类」则每个根分类各成一个一级菜单项。", generateFromRoot: "全部根分类", menuItems: "菜单项 (树形结构)", customUrl: "自定义链接", category: "分类目录", article: "文章内容", selectArticle: "选择文章", label: "标签名", url: "链接地址", username: "用户名", password: "密码", role: "权限角色", leaveBlankToKeep: "在此留空则不修改密码", admin: "文章管理员", superadmin: "超级管理员", site_name: "网站名称", subtitle: "副标题", icp_record: "备案号", mourning_mode: "哀悼模式", articleDataFields: "文章数据字段", articleDataFieldsDesc: "定义该分类下文章的自定义数据字段。", editorHint: "编辑器提示", editorHintDesc: "markdown，会显示在该分类文章的正文编辑器上方 —— 用来说明正文里要按什么格式写。", editorHintPlaceholder: "例：说明正文需要包含哪些块、格式是什么", fieldTitle: "显示名", fieldTypeText: "单行文本", fieldTypeTextarea: "多行文本", fieldTypeNumber: "数字", fieldTypeAttachment: "附件", extraFields: "自定义字段", exportTitle: "数据导出", exportDesc: "将全站数据导出为 JSON 文件。导入功能仅在系统初始化时可用。", exportAll: "导出全部数据", storageProvider: "存储引擎", storageConfig: "存储配置", storageConfigDesc: "配置上传文件的存储位置。切换存储引擎不会迁移已有文件。", testConnection: "测试连接", testSuccess: "连接成功", testFailed: "连接失败", testing: "测试中...", themeSettings: "主题设置", themeSettingsDesc: "当前前台主题声明的可配置项。" },
    dashboard: { welcome: "欢迎回来", overviewPrefix: "这是您的系统仪表盘，快速掌控站点的各项数据动态。", totalArticles: "内容文章数", schemasActive: "注册模型数", totalCategories: "分类库区总计", totalFiles: "媒体附件规模", totalUsers: "站务管理员数", recentArticles: "最新发布记录", quickActions: "工作台入口", systemStatus: "关键服务运行" },
    auth: { logout: "退出登录", signIn: "登录", useId: "使用您的 NFCMS ID登录。", username: "用户名", password: "密码", loginFailed: "登录失败", loginSuccess: "登录成功", fieldsRequired: "所有字段都是必填的。" },
    front: { home: "首页", readMore: "阅读全文", back: "返回首页", publishedOn: "发布于", by: "作者：", locked: "会员内容", lockedHint: "登录后阅读" },
    gate: { title: "受限内容", message: "该内容未公开。请使用已获授权的账号登录后继续访问。", login: "登录", backHome: "← 返回首页" },
    article: { properties: "文章属性", history: "版本历史", scheduledAt: "计划于 {time} 自动发布。", publishedAtHint: "留空则首次发布时自动填写。" },
    menu: {},
    user: { new: "新建管理员" },
    role: { super_admin: "超级管理员", admin: "管理员", user: "普通用户", editor: "编辑者" }
  }
};

// Single source of truth for the active locale (chosen once at startup).
export const activeLocale = navigator.language.startsWith('zh') ? 'zh' : 'en';

const i18n = createI18n({
  legacy: false,
  locale: activeLocale,
  fallbackLocale: 'en',
  messages,
});

// PrimeVue's own locale (calendar/paginator/etc. labels) is separate from vue-i18n.
// We only override zh; en is PrimeVue's built-in default (pass `undefined`).
const primevueLocaleZh = {
  firstDayOfWeek: 1,
  dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
  monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  today: '今天',
  clear: '清除',
};

export const primevueLocale = activeLocale === 'zh' ? primevueLocaleZh : undefined;

export default i18n;
